name: CI

on: [push, pull_request]

jobs:
  ci-x86:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install -y clang-tools valgrind

      - name: Tests
        run: make check

      - name: Tests (Sanitizers)
        run: make check-asan

      - name: Clang Analyzer
        run: make scan

      - name: Valgrind
        run: make valgrind

  ci-arm64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static binfmt-support gcc-aarch64-linux-gnu libc6-dev-arm64-cross

      - name: Tests (ARM64 Emulation)
        env:
          QEMU_LD_PREFIX: /usr/aarch64-linux-gnu
          CPPFLAGS: -DOBLAS_NEON
        run: |
          make CC=aarch64-linux-gnu-gcc CFLAGS="-O3 -g -std=c11 -Wall -I. -Ideps/obl -funroll-loops -ftree-vectorize" check

  ci-riscv64:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt update
          sudo apt install -y qemu-user-static binfmt-support gcc-riscv64-linux-gnu libc6-dev-riscv64-cross

      - name: Tests (RISCV64 Emulation)
        env:
          QEMU_LD_PREFIX: /usr/riscv64-linux-gnu
        run: |
          make CC=riscv64-linux-gnu-gcc CFLAGS="-O3 -g -std=c11 -Wall -I. -Ideps/obl -march=rv64gcv -mabi=lp64d -funroll-loops -ftree-vectorize" check

  ci-avx2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Tests (AVX2)
        run: make check CPPFLAGS="-DOBLAS_AVX2" CFLAGS="-O3 -g -std=c11 -Wall -I. -Ideps/obl -mavx2"

  ci-avx512:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download Intel SDE
        run: |
          wget https://github.com/nihui/ncnn-assets/releases/download/toolchain/sde-external-10.8.0-2026-03-15-lin.tar.xz
          tar xf sde-external-10.8.0-2026-03-15-lin.tar.xz
          echo "$PWD/sde-external-10.8.0-2026-03-15-lin" >> $GITHUB_PATH

      - name: Tests (AVX-512 Emulation)
        run: make RUN="sde64 -skx --" check CPPFLAGS="-DOBLAS_AVX512" CFLAGS="-O3 -g -std=c11 -Wall -I. -Ideps/obl -mavx512f -mavx512bw"
